// Copyright (c) 2026 TollWarden, LLC. All rights reserved.
// SPDX-License-Identifier: BUSL-1.1
/**
 * Replay detection: tracks payment nonces and blocks reuse.
 * Key is scoped by network + payer (when known) so distinct payers with
 * coincidentally equal nonces don't collide. The network part is networkKey,
 * so one authorization presented under "base" and again under "eip155:8453"
 * is the same nonce on the same chain.
 */
import type { CheckResult, PaymentDetails } from "../types.ts";
import type { Store } from "../store.ts";
import { networkKey } from "./asset.ts";

export function checkReplay(
  payment: PaymentDetails,
  store: Store,
  scanId: string,
  ttlHours: number,
  phase?: "pre_sign" | "post_sign",
): CheckResult {
  if (!payment.nonce) {
    // Pre-signature scans structurally cannot have a nonce: EIP-3009 nonces
    // are generated by the x402 client at signing time. An honest
    // scan-before-pay flow must not dead-end on a permanent flag for that.
    if (phase === "pre_sign") {
      return {
        id: "replay.pre_sign",
        name: "Replay detection",
        verdict: "allow",
        severity: "info",
        reason:
          "Pre-signature scan: the payment nonce is generated at signing time, so replay checking is deferred. Reused-authorization replay is still rejected on-chain by EIP-3009 nonce uniqueness; re-scan with the nonce post-sign for TollWarden-side coverage.",
      };
    }
    return {
      id: "replay.no_nonce",
      name: "Replay detection",
      verdict: "flag",
      severity: "low",
      reason:
        "No nonce supplied with the payment payload, so replay protection cannot be verified. Include the payment nonce for full coverage — or set context.phase to 'pre_sign' if the payment has not been signed yet.",
    };
  }

  // Nonce TTL pruning runs on the Store's maintenance timer, not here, so the
  // hot path stays O(1) instead of O(nonces) per request (audit H-4).
  void ttlHours;
  const payer = (payment.payer ?? "").toLowerCase();
  const key = `${networkKey(payment.network) ?? "?"}:${payer}:${payment.nonce}`;
  // Records written before network keys were normalized (2026-10-02) used the
  // network string as presented. Honor them until they age out of the nonce
  // TTL; this fallback can go once that deploy is older than NONCE_TTL_HOURS.
  const legacyKey = `${payment.network ?? "?"}:${payer}:${payment.nonce}`;
  const existing = store.nonces.get(key) ?? (legacyKey !== key ? store.nonces.get(legacyKey) : undefined);

  if (existing) {
    existing.times_seen += 1;
    store.markDirty();
    return {
      id: "replay.nonce_reuse",
      name: "Replay detection",
      verdict: "block",
      severity: "critical",
      reason: `Nonce reuse detected: this nonce was first seen ${existing.first_seen} (scan ${existing.scan_id}) and has now appeared ${existing.times_seen} times. A reused nonce means a stale or captured payment authorization is being replayed.`,
      details: {
        nonce: payment.nonce,
        first_seen: existing.first_seen,
        first_scan_id: existing.scan_id,
        times_seen: existing.times_seen,
      },
    };
  }

  store.nonces.set(key, {
    first_seen: new Date().toISOString(),
    times_seen: 1,
    scan_id: scanId,
  });
  store.markDirty();

  return {
    id: "replay.clean",
    name: "Replay detection",
    verdict: "allow",
    severity: "info",
    reason: "Nonce has not been seen before within the tracking window.",
  };
}
